services/web/web_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import DateField
# from wtforms import Form, StringField, PasswordField, validators, SubmitField
from wtforms import SubmitField


class DateForm(FlaskForm):
    dt = DateField('Escolhe uma data Ex: 2018-06-15 ',
                   format='%Y-%m-%d',
                   id="datepicker",
                   render_kw={'autocomplete': 'off'})

    submit = SubmitField('Go')

services/web/web_app/__init__.py
import logging
import os
from logging.handlers import SMTPHandler, RotatingFileHandler

from flask import Flask
# from flask_moment import Moment
from flask_babel import Babel, lazy_gettext as _l
from flask_bcrypt import Bcrypt
# from flask_mail import Mail
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from . import config

# from elasticsearch import Elasticsearch
# from redis import Redis
# import rq

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
bcrypt = Bcrypt()
login.login_view = 'auth.login'
login.login_message = _l('Please log in to access this page.')
# mail = Mail()
bootstrap = Bootstrap()
# moment = Moment()
babel = Babel()


def create_homedash_app(config_class=config.Config):
    homedash = Flask(__name__)
    homedash.config.from_object(config_class)
    ##Change stating path for another
    ## TODO: Change this if homedash dos not have nothing
    a_new_static_path = '/'+homedash.config['NGINX_URL']+"/static/"

    # Set the static_url_path property.
    homedash.static_url_path = a_new_static_path

    # Remove the old rule from Map._rules.
    for rule in homedash.url_map.iter_rules('static'):
        homedash.url_map._rules.remove(rule)  # There is probably only one.

    # Remove the old rule from Map._rules_by_endpoint. In this case we can just 
    # start fresh.
    homedash.url_map._rules_by_endpoint['static'] = []  

    # Add the updated rule.
    homedash.add_url_rule(f'{a_new_static_path}/<path:filename>',
                    endpoint='static',
                    view_func=homedash.send_static_file)

    db.init_app(homedash)
    migrate.init_app(homedash, db)
    login.init_app(homedash)
    bcrypt.init_app(homedash)
    # mail.init_app(app)
    bootstrap.init_app(homedash)
    # moment.init_app(app)
    babel.init_app(homedash)
    # app.elasticsearch = Elasticsearch([app.config['ELASTICSEARCH_URL']]) \
    # if app.config['ELASTICSEARCH_URL'] else None
    # app.redis = Redis.from_url(app.config['REDIS_URL'])
    # app.task_queue = rq.Queue('microblog-tasks', connection=app.redis)

    # from app.errors import blueprint as errors_blueprint
    # app.register_blueprint(errors_blueprint)

    from .api import bp as api_bp
    homedash.register_blueprint(api_bp, url_prefix='/'+homedash.config['NGINX_URL']+'/api')

    from .auth import blueprint as auth_blueprint
    homedash.register_blueprint(auth_blueprint, url_prefix='/'+homedash.config['NGINX_URL'])

    from .main import blueprint as main_blueprint
    homedash.register_blueprint(main_blueprint, url_prefix='/'+homedash.config['NGINX_URL'])

    # from app.api import blueprint as api_blueprint
    # app.register_blueprint(api_blueprint, url_prefix='/api')

    if not homedash.debug and not homedash.testing:
        if homedash.config['MAIL_SERVER']:
            auth = None
            if homedash.config['MAIL_USERNAME'] or homedash.config['MAIL_PASSWORD']:
                auth = (homedash.config['MAIL_USERNAME'],
                        homedash.config['MAIL_PASSWORD'])
            secure = None
            if homedash.config['MAIL_USE_TLS']:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost=(homedash.config['MAIL_SERVER'], homedash.config['MAIL_PORT']),
                fromaddr='no-reply@' + homedash.config['MAIL_SERVER'],
                toaddrs=homedash.config['ADMINS'], subject='Microblog Failure',
                credentials=auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            homedash.logger.addHandler(mail_handler)

        if homedash.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            homedash.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/microblog.log',
                                               maxBytes=10240, backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            homedash.logger.addHandler(file_handler)
        homedash.config['TEMPLATES_AUTO_RELOAD'] = True
        homedash.logger.setLevel(logging.INFO)
        homedash.logger.info('Jdvalverde website startup')

    return homedash


app = create_homedash_app()

services/web/web_app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from web_app.api import controllers, tokens, apierrors

services/web/web_app/api/auth.py
from flask import g
from flask_httpauth import HTTPBasicAuth, HTTPTokenAuth
from flask_login import current_user
from web_app.models import User
from web_app.api.apierrors import error_response

basic_auth = HTTPBasicAuth()
token_auth = HTTPTokenAuth()


@basic_auth.verify_password
def verify_password(username, password):
    user = User.query.filter_by(username=username).first()
    if user is None:
        return False
    g.current_user = user
    return user.check_password(password)


@basic_auth.error_handler
def basic_auth_error():
    return error_response(401)


@token_auth.verify_token
def verify_token(token):
    g.current_user = User.check_token(token) if token else None
    return g.current_user is not None

services/web/web_app/api/controllers.py
from flask import jsonify
from flask import render_template, request
from web_app.models import User, PalacouloDoorStatus, PortoDoorStatus
from web_app.api import bp
from flask import url_for
from web_app import db
from web_app.api.apierrors import bad_request
from web_app.api.auth import token_auth

@bp.route('/users/<int:id>', methods=['GET'])
@token_auth.login_required
def get_user(id):
    return jsonify(User.query.get_or_404(id).to_dict())

@bp.route('/controller', methods=['POST'])
@token_auth.login_required
def update_controller():
    data = request.get_json() or {}
    print(data)
    if 'controller' not in data or 'status' not in data:
        return bad_request('must include username, email and password fields')

    if "Porto" in data["controller"]:
        controller = PortoDoorStatus(data["status"])
    elif "Palacoulo" in data["controller"]:
        controller = PalacouloDoorStatus(data["status"])

    db.session.add(controller)
    db.session.commit()
    response = jsonify(controller.to_dict())
    response.status_code = 201
    return response

def update_user(id):
    user = User.query.get_or_404(id)
    data = request.get_json() or {}
    if 'username' in data and data['username'] != user.username and \
            User.query.filter_by(username=data['username']).first():
        return bad_request('please use a different username')
    if 'email' in data and data['email'] != user.email and \
            User.query.filter_by(email=data['email']).first():
        return bad_request('please use a different email address')
    user.from_dict(data, new_user=False)
    db.session.commit()
    return jsonify(user.to_dict())

services/web/web_app/main/__init__.py
from flask import Blueprint

blueprint = Blueprint('app', __name__)

from web_app.main import routes

# url_prefix='/homecontrol'

services/web/web_app/main/routes.py
import time

import threading

from datetime import date
from datetime import datetime

from flask import url_for, redirect, render_template, request, jsonify
from flask_login import login_required
from sqlalchemy import func

from web_app.config import Config
from web_app import db
from web_app.main import blueprint
from web_app.main.forms import DateForm
from web_app.main.pi_utils import measure_temp
from web_app.models import PortoDoorStatus, PalacouloDoorStatus
from web_app.socket_connection.socket_connection import SocketConnection

@blueprint.route('/', methods=['GET', 'POST'])
@blueprint.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    return redirect(url_for('app.overview'))


@blueprint.route('/', methods=['GET', 'POST'])
@blueprint.route('/overview')
@login_required
def overview():
    door = PalacouloDoorStatus.query.order_by(PalacouloDoorStatus.id.desc()).first()
    return render_template('dashboard.html',
                           status=door,
                           curr=1)


@blueprint.route('/history')
@login_required
def history():
    return render_template('construction.html')


def open_worker():
    client = SocketConnection(Config.INTERNAL_SERVER, Config.INTERNAL_PORT)
    #client.send_msg("op_<0_1_0_2_1>")
    # location_actuator_command
    client.send_msg("palacoulo_garagedoor_open")


@blueprint.route('/control/open_porto_door')
@login_required
def open_porto_door():
    t = threading.Thread(target=open_worker)
    t.start()

    return redirect(url_for('app.overview'))


@blueprint.route('/control/garagedoor')
@login_required
def change_garage_door():
    door = PalacouloDoorStatus.query.order_by(PalacouloDoorStatus.id.desc()).first()
    print("Ola")
    door_status = door.door_status

    if door_status == 0:
        print("Opening")
        #send_open()
    elif door_status == 1:
        print("Still Opening")
    elif door_status == 2:
        print("Closing")
        #send_open()
    elif door_status == 3:
        print("Still closing")

    # if DEBUG:
    #    print("asdfasdf")
    #    door_status += 1
    #    if door_status == 4:
    #        door_status = 0

    new_door_status = PalacouloDoorStatus(
        date=datetime.now(),
        door_status=door_status
    )
    db.session.add(new_door_status)
    db.session.commit()

    # TODO: Fix Following
    return redirect(url_for('app.overview'))


@blueprint.route('/<location>/date/', methods=['GET', 'POST'])
@login_required
def porto_overview(location):
    value = 0
    form = DateForm()
    page = request.args.get('page', 1, type=int)
    get_date = request.args.get('submit_date', type=str)

    # print("GET:")
    # print(get_date)
    # print("Today:")
    # print(today_string)

    if get_date:
        submit_date = datetime.strptime(get_date, '%Y-%m-%d').strftime('%x')
        submit_date_u = get_date
    else:
        submit_date = form.dt.data.strftime('%x') if form.validate_on_submit() else date.today().strftime('%x')
        submit_date_u = form.dt.data if form.validate_on_submit() else date.today()

    # print(submit_date_u)
    # print(submit_date)

    door_status = \
        PalacouloDoorStatus.query.filter(func.date(PalacouloDoorStatus.date) == submit_date_u).paginate(page, 10, False) \
        if "palacoulo" in location else \
        PortoDoorStatus.query.filter(func.date(PortoDoorStatus.date) == submit_date_u).paginate(page, 10, False)

    door = PalacouloDoorStatus.query.order_by(PalacouloDoorStatus.id.desc()).first()

    if not door_status:
        print("Problems")
        # abort(404)

    # print(door_status.items)
    for row in door_status.items:
        if row.date.strftime('%x') == submit_date:
            #        print("1")
            value = 1

    next_url = url_for('app.porto_overview', location=location, page=door_status.next_num, submit_date=submit_date_u) \
        if door_status.has_next else None
    prev_url = url_for('app.porto_overview', location=location, page=door_status.prev_num, submit_date=submit_date_u) \
        if door_status.has_prev else None

    # pagination = Pagination(date, Config.PER_PAGE, count)
    return render_template('table_date_overview.html',
                           status=door,
                           value=value,
                           type=location,
                           form=form,
                           submit_date=submit_date,
                           door_table=door_status.items,
                           next_url=next_url,
                           prev_url=prev_url)

services/web/web_app/templates/cards/__main_card.html
        <div id="row" class="col-md-4 mb-3">
            <div class="card text-center">
                {% block cardinner %}{% endblock %}
            </div>
</div>

services/web/web_app/templates/cards/_palacoulo_door_status.html
<tr>
     <td class="title">{{ door.get_hour() }}</td>
    {% if door is not none %}
        {% if door.get_door_status() == 1 %}
                <td class="title">Fechada</td>
        {% elif door.get_door_status() == 2 %}
                <td class="title">Abrir</td>
        {% elif door.get_door_status() == 0 %}
                 <td class="title">Aberta</td>
        {% elif door.get_door_status() == 3 %}
                 <td class="title">Fechar</td>
        {% endif %}
    {% else %}
        NONE
    {%endif %}
</tr>

services/web/web_app/templates/cards/_porto_door_status.html
<tr>
    {% if door is not none %}
     <td class="title">{{ door.get_hour() }}</td>

    {% if door.get_opened_status() == 'opening_remotaly' %}
            <td class="title">Controlado Remotamente</td>
    {% elif door.get_opened_status() == 'opening_manualy' %}
            <td class="title">Aberto com Campainha</td>
    {% elif door.get_opened_status() == 'door_belt' %}
            <td class="title">Tocou Campainha</td>
    {% elif door.get_opened_status() == 'door_open' %}
             <td class="title">Porta 3 andar Aberta</td>
    {% else %}
        <td class="title"> {{ door.get_opened_status() }} </td>
    {% endif %}
    {% endif %}

</tr>

services/web/web_app/templates/cards/_users.html
<tr>
    <td class="title">{{ user.id }}</td>
    <td class="title">{{ user.username }}</td>
    <td class="title">{{ user.email }}</td>
    <td class="title">{{ user.token }}</td>
    <td> <a href="{{ url_for('auth.delete_user', token=user.id) }}"> delete </a> </td>
</tr>

services/web/web_app/templates/cards/boken_graph.html
{% extends "cards/__main_card.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block cardinner %}
    <div class="card-header">
        Graph
    </div>
    <div class="card-body">
     {% for plot in plots %}
        {% for part in plot %}
            {{part | safe}}
        {% endfor %}
    {% endfor %}
    </div>
{% endblock %}

services/web/web_app/templates/cards/date_opened_table.html
<div class="card-header">{{ type +" em " + submit_date }}</div>

{#
                    <form method="post" action="{{ url_for('app.porto_overview',location=type) }}">
                        {{ form.hidden_tag() }}
                        {{ form.dt(class="date") }}
                        <button type="submit">Go</button>
                    </form>
    #}
<div class="card-body">
    {{ wtf.quick_form(form) }}
    <div class="table-responsive m-3">
        <table class="table table-striped table-sm">
            {% if door is not none or value == 1  %}
                {% for door in door_table %}
                    {% if submit_date in door.date.strftime('%x') %}
                        {% include 'cards/_'+type+'_door_status.html' %}
                    {% endif %}
                {% endfor %}
                {% if prev_url %}
                    <a href="{{ prev_url }}"> Trás </a>
                {% endif %}
                {% if next_url %}
                    <a href="{{ next_url }}"> Frente </a>
                {% endif %}
            {% else %}
                <p>&mdash;Não há informações disponíveis para esta data&mdash;</p>
            {% endif %}
        </table>
    </div>
</div>

services/web/web_app/templates/cards/palacoulo_garage_door_opener.html
{% extends "cards/__main_card.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block cardinner %}
    <div class="card-header">
        Palacoulo
    </div>
    <div class="card-body">
    <p> Porta está <span style="color:
                {% if status.door_status == 1 or status is none %}
                 red; ">   Fechada</span></p>
                    <a href= {{ url_for('app.change_garage_door') }} class="btn btn-primary" >Abrir</a>
                {% elif status.door_status == 2 %}
                 yellow; ">   A Abrir</span></p>
                    <a href= {{ url_for('app.change_garage_door') }} class="btn btn-primary" >Fechar</a>
                    <p> distance : {{ distance }}</p>
                {% elif status.door_status == 0 %}
                 green; ">   Aberta</span></p>
                    <a href= {{ url_for('app.change_garage_door') }} class="btn btn-primary" >Fechar</a>
                {% elif status.door_status == 3 %}
                yellow; ">    A fechar</span></p>
                    <a href= {{ url_for('app.change_garage_door') }} class="btn btn-primary" >Abrir</a>
                {% endif %}
    </div>
{% endblock %}

services/web/web_app/templates/cards/porto_door_opener.html
{% extends "cards/__main_card.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block cardinner %}
    <div class="card-header">
        Abertura de Porta Porto
    </div>
    <div class="card-body">
        <a href={{ url_for('app.open_porto_door') }} class="btn btn-primary" >Abrir</a>
    </div>
{% endblock %}

services/web/web_app/templates/cards/temperature_pi_gauge.html
{% extends "cards/__main_card.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block cardinner %}
    <div class="card-header">
        Abertura de Porta Porto
    </div>
    <div class="card-body">
       <div class="gauge">
           <canvas width="70" height="70" id="canvas-preview"></canvas>
           <div id="preview-textfield" style="font-size: 15px;">0%</div>
       </div>
    </div>
{% endblock %}